"""Update PRODUCT.md chunking section"""
import os

# Read current PRODUCT.md
path = os.path.join(os.path.dirname(__file__), '..', 'PRODUCT.md')
with open(path, encoding='utf-8') as f:
    content = f.read()
    lines = content.split('\n')

# Find section boundaries
start = end = None
for i, l in enumerate(lines):
    if l.strip().startswith('### 文档分块策略'):
        start = i
    if l.strip().startswith('## 数据库设计'):
        end = i
        break

if start is None or end is None:
    print(f"Not found: start={start}, end={end}")
    exit(1)

new_section = []
new_section.append('### 文档分块策略')
new_section.append('')
new_section.append('#### 总流程图')
new_section.append('')
new_section.append('```text')
new_section.append('                        用户上传文档')
new_section.append('                             |')
new_section.append('                             v')
new_section.append('              +-------------------------------+')
new_section.append('              |    MIME 类型识别(扩展名)      |')
new_section.append('              |   .pdf / .docx / .md / .txt   |')
new_section.append('              +-------------------------------+')
new_section.append('                             |')
new_section.append('            +----------------+----------------+')
new_section.append('            |                |                |')
new_section.append('            v                v                v')
new_section.append('      +----------+    +----------+    +----------+')
new_section.append('      |PDFParser |    |DocxParser|    | MD/TXT   |')
new_section.append('      |          |    |          |    | Parser   |')
new_section.append('      +-----+----+    +-----+----+    +-----+----+')
new_section.append('            |               |               |')
new_section.append('            v               v               v')
new_section.append('     +-------------+  +-----------+  +-----------+')
new_section.append('     |采样5页判断类型|  |识别Heading |  |识别#标题   |')
new_section.append('     |p1/5/10/20/50|  |样式1/2/3  |  |(MD only)  |')
new_section.append('     +--+-------+---+  +-----+-----+  +-----+-----+')
new_section.append('        |       |             |               |')
new_section.append('     >=50字符 全部<50         |               |')
new_section.append('        |       |             |               |')
new_section.append('        v       v             v               v')
new_section.append('    文本型   扫描件     全文合并注入     全文合并注入')
new_section.append('   pdfplumber 逐页OCR   [章>节]路径     [章>节]路径')
new_section.append('   逐页提取   (百度)    1个ParsedPage    1个ParsedPage')
new_section.append('        |       |             |               |')
new_section.append('        +-------+-------------+---------------+')
new_section.append('                        |')
new_section.append('             N个 ParsedPage(page_number, text)')
new_section.append('                        |')
new_section.append('                        v')
new_section.append('              +---------------------+')
new_section.append('              |      Chunker        |')
new_section.append('              |  chunk_text(text,    |')
new_section.append('              |   page_number,       |')
new_section.append('              |   chunk_size=500,    |')
new_section.append('              |   overlap=60,        |')
new_section.append('              |   file_type)         |')
new_section.append('              +----------+----------+')
new_section.append('                         |')
new_section.append('                         v')
new_section.append('              +---------------------+')
new_section.append('              |  原子保护:表格/列表  |')
new_section.append('              |  正则识别,包裹防切   |')
new_section.append('              +----------+----------+')
new_section.append('                         |')
new_section.append('                         v')
new_section.append('              +---------------------+')
new_section.append('              |  检测章节标记?       |')
new_section.append('              |  [章>节]/#/第X章/条  |')
new_section.append('              +------+------+-------+')
new_section.append('                     |YES   |NO')
new_section.append('                     v      |')
new_section.append('              +---------+   |')
new_section.append('              |结构分块  |   |')
new_section.append('              |按标题切分|   |')
new_section.append('              |超长递归字符|  |')
new_section.append('              |携带章节路径|  |')
new_section.append('              +----+----+   |')
new_section.append('                   |        |')
new_section.append('                   |   +----+-----------+')
new_section.append('                   |   |>2048字符+>=10句?|')
new_section.append('                   |   +----+------+----+')
new_section.append('                   |       YES     NO')
new_section.append('                   |        |       |')
new_section.append('                   |        v       v')
new_section.append('                   |   +--------+ +----------+')
new_section.append('                   |   |语义分块 | |递归字符   |')
new_section.append('                   |   |Embed句子| |分块(兜底)  |')
new_section.append('                   |   |余弦相似度| |500/60     |')
new_section.append('                   |   |percentile| |按段落->句子 |')
new_section.append('                   |   |10%阈值切| |->字符优先   |')
new_section.append('                   |   +---+----+ +-----+-----+')
new_section.append('                   |       |            |')
new_section.append('                   +-------+------------+')
new_section.append('                           |')
new_section.append('                           v')
new_section.append('                list[Chunk] (text, page, section_path, content_type)')
new_section.append('                           |')
new_section.append('                           v')
new_section.append('              +-------------------------+')
new_section.append('              |      Pipeline 入库       |')
new_section.append('              |  32条/批 Embed->写入      |')
new_section.append('              +----------+--------------+')
new_section.append('                         |')
new_section.append('            +------------+------------+')
new_section.append('            |            |            |')
new_section.append('            v            v            v')
new_section.append('       +--------+  +---------+  +----------+')
new_section.append('       | Milvus |  |  BM25   |  | SQLite   |')
new_section.append('       |向量索引|  |关键词索引|  |document_ |')
new_section.append('       |COSINE  |  |rank-bm25|  |chunks表  |')
new_section.append('       +--------+  +---------+  +----------+')
new_section.append('```')
new_section.append('')
new_section.append('#### 各节点说明')
new_section.append('')
new_section.append('| 节点 | 作用 | 输入 | 输出 | 关键参数 |')
new_section.append('|------|------|------|------|---------|')
new_section.append('| MIME识别 | 扩展名路由到对应Parser | 原始文件 | Parser实例 | .pdf/.docx/.md/.txt |')
new_section.append('| PDFParser | 提取PDF文本,扫描件走OCR | PDF文件 | list[ParsedPage] | -- |')
new_section.append('| PDF采样预判 | 避免对文本型PDF逐页试OCR | PDF文件 | is_scanned(bool) | 采样页:[1,5,10,20,50], 阈值:50字符 |')
new_section.append('| 百度OCR | 扫描件页面文字识别 | PNG(bytes) | 识别文本 | DPI:200, lang:CHN_ENG |')
new_section.append('| DocxParser | 提取DOCX文本+标题结构 | DOCX文件 | 1个ParsedPage(带[章>节]路径) | Heading样式1/2/3 |')
new_section.append('| MD Parser | 提取MD文本+标题结构 | MD文件 | 1个ParsedPage(带#标题路径) | # 标题行 |')
new_section.append('| TXT Parser | 纯文本读取 | TXT文件 | 1个ParsedPage | UTF-8 |')
new_section.append('| 原子保护 | 表格/列表不跨chunk切碎 | 原始文本 | 包裹后文本 | 正则:表格行 ^\\\\|.+\\\\|$ 列表 ^[-*+\\\\d] |')
new_section.append('| 章节检测 | 判断是否走结构分块 | 文本 | bool | 标记: [章>节] / # / 第X章/条 |')
new_section.append('| 结构分块 | 按标题边界切分,携带章节路径 | 文本+标题标记 | list[Chunk] | 超长内部递归 chunk_size=500 |')
new_section.append('| 语义分块 | 按话题相似度切分 | 句子列表 | list[Chunk] | >2048字符, >=10句, percentile=10% |')
new_section.append('| 递归字符分块 | 兜底,段落->句子->字符优先级切 | 文本 | list[Chunk] | chunk_size=500, overlap=60 |')
new_section.append('| Pipeline入库 | 批量Embed->写向量库+DB | list[Chunk] | -- | 32条/批 |')
new_section.append('')
new_section.append('#### Chunk元数据字段')
new_section.append('')
new_section.append('| 字段 | 说明 | 来源 | 有结构(DOCX/MD) | 无结构(PDF/TXT) |')
new_section.append('|------|------|------|:--:|:--:|')
new_section.append('| text | 分块文本内容 | chunker | Y | Y |')
new_section.append('| page_start | 起始页码 | Parser | Y(DOCX=1) | Y |')
new_section.append('| page_end | 结束页码 | Parser | Y | Y |')
new_section.append('| section_path | 章节路径 | 结构分块 | Y [章>节] | N |')
new_section.append('| content_type | 内容类型 | 结构分块 | Y(prose/clause) | Y(prose) |')
new_section.append('| token_count | 字符数 | chunker | Y | Y |')
new_section.append('')
new_section.append('> PDF/TXT缺section_path是已知局限：pdfplumber提取纯文本不保留标题层级；TXT本身无结构标记。')
new_section.append('')
new_section.append('#### 关键参数汇总')
new_section.append('')
new_section.append('| 参数 | 值 | 用途 |')
new_section.append('|------|-----|------|')
new_section.append('| chunk_size | 500字符 | 通用prose,递归分块和结构分块超长回退 |')
new_section.append('| overlap | 60字符(12%) | 相邻chunk重叠 |')
new_section.append('| OCR阈值 | 50字符/页 | 判断单页是否扫描件 |')
new_section.append('| OCR采样页 | [1,5,10,20,50] | 预判整个PDF类型 |')
new_section.append('| OCR DPI | 200 | PyMuPDF渲染分辨率 |')
new_section.append('| Embed批大小 | 32 | 智谱Embedding-3限制64,留余量 |')
new_section.append('| 语义最低字符 | 2048 | 短文本不值得调Embed API |')
new_section.append('| 语义最低句子 | 10 | 句子太少无法计算相似度 |')
new_section.append('| 语义percentile | 10% | 最低10%相似度处切分 |')
new_section.append('| 硬上限 | chunk_size*1.5 | 单组超过强制回退字符切分 |')
new_section.append('')

# Rebuild file
new_lines = lines[:start] + new_section + lines[end:]
with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(new_lines))

section_lines = len(new_section)
print(f"Updated. Section {start+1}-{start+section_lines} ({section_lines} lines)")
